yieldprotocol/vault-v2

- contracts/Join.sol
- contracts/JoinFactory.sol
- package.json
- test/011_oracles.ts
- test/021_join.ts
- test/022_join_flash.ts
- test/031_fyToken.ts
- test/051_cauldron_admin.ts
- test/060_ladle_admin.ts
- test/066_remove_and_repay.ts
- test/shared/fixtures.ts
- test/shared/helpers.ts
- yarn.lock
@albertocuestacanada When you are available, I'd very much like you to help me with the tests for this branch, I've run out of ideas why some of tx's revert.
For [this](https://github.com/code-423n4/2021-05-yield-findings/issues/70).
> Fix code423n4/70

- contracts/Cauldron.sol
- test/054_cauldron_stir.ts
Mitigates finding https://github.com/code-423n4/2021-05-yield-findings/issues/7.
> Mitigate finding

- contracts/Ladle.sol
- hardhat.config.ts
- src/helpers.ts
- src/ladleWrapper.ts
- test/063_ladle_vaults.ts
- test/064_ladle_stir.ts
- test/069_ladle_permit.ts
- test/070_ladle_batch.ts
- test/shared/fixtures.ts
[Code Arena Issue 43](https://github.com/code-423n4/2021-05-yield-findings/issues/43)
> Fix vault build griefing attack

- contracts/Cauldron.sol
Fixes [Code Arena 59](https://github.com/code-423n4/2021-05-yield-findings/issues/59)
> fix: check seriesId, ilkId, and vaultId can't be zero

- contracts/Cauldron.sol
- contracts/Join.sol
- contracts/Witch.sol
- contracts/oracles/chainlink/ChainlinkMultiOracle.sol
- contracts/oracles/chainlink/ChainlinkOracle.sol
- contracts/oracles/compound/CompoundChiOracle.sol
- contracts/oracles/compound/CompoundMultiOracle.sol
- contracts/oracles/compound/CompoundRateOracle.sol
- contracts/oracles/uniswap/UniswapV3Oracle.sol
Fixes part of [c5 60](https://github.com/code-423n4/2021-05-yield-findings/issues/60)
> tweak: use external where possible

- contracts/Ladle.sol
Fix [c4-56](https://github.com/code-423n4/2021-05-yield-findings/issues/56)
> tweak: remove unnecessary MSTORE

- contracts/FYToken.sol
Fixes [c4 67](https://github.com/code-423n4/2021-05-yield-findings/issues/67)
> fix: remove unnecessary `unchecked`

- contracts/Join.sol
- test/022_join_flash.ts
- test/shared/fixtures.ts
- test/shared/helpers.ts
Fixes [c4 53](https://github.com/code-423n4/2021-05-yield-findings/issues/53)
> tweak: disable join flash loans by default

- contracts/oracles/uniswap/UniswapV3Oracle.sol
Fixes [c4 37](https://github.com/code-423n4/2021-05-yield-findings/issues/37)
> fix: _peek should be private

- contracts/FYToken.sol
- contracts/Join.sol
- contracts/Wand.sol
- contracts/constants/Constants.sol
- contracts/oracles/compound/CompoundMultiOracle.sol
Fixes [c4 3](https://github.com/code-423n4/2021-05-yield-findings/issues/3) and [c4 13](https://github.com/code-423n4/2021-05-yield-findings/issues/13)
> fix: use constants where appropriate

- contracts/oracles/chainlink/ChainlinkMultiOracle.sol
- contracts/oracles/chainlink/ChainlinkOracle.sol
- contracts/oracles/compound/CompoundChiOracle.sol
- contracts/oracles/compound/CompoundMultiOracle.sol
- contracts/oracles/compound/CompoundRateOracle.sol
- contracts/oracles/uniswap/UniswapV3Oracle.sol
Fixes [c4 19](https://github.com/code-423n4/2021-05-yield-findings/issues/19)
> fix: oracle.get is transactional

- contracts/Ladle.sol
- contracts/Wand.sol
Fixes [c4 9](https://github.com/code-423n4/2021-05-yield-findings/issues/9)
> fix: remove TODOs, which are now github issues

- contracts/Ladle.sol
- contracts/Wand.sol
- contracts/Witch.sol
- hardhat.config.ts
- package.json
- test/081_witch.ts
- test/shared/fixtures.ts
- yarn.lock
Now the Witch stores different duration, initialOffer and dust for each collateral that can be liquidated.
> feat: configure witch parameters per ilk

- contracts/FYTokenFactory.sol
- contracts/JoinFactory.sol
- contracts/Ladle.sol
- contracts/Wand.sol
- contracts/Witch.sol
- hardhat.config.ts
- package.json
- test/021_join.ts
- test/022_join_flash.ts
- test/051_cauldron_admin.ts
- test/060_ladle_admin.ts
- test/081_witch.ts
- test/shared/fixtures.ts
- yarn.lock
Having a FYTokenFactory reduces the deployment size of Wand, and provides a better separation of concerns.
> FYTokenFactory

- contracts/mocks/oracles/OracleMock.sol
- contracts/oracles/chainlink/ChainlinkMultiOracle.sol
- contracts/oracles/chainlink/ChainlinkOracle.sol
- contracts/oracles/composite/CompositeMultiOracle.sol
- contracts/oracles/compound/CompoundChiOracle.sol
- contracts/oracles/compound/CompoundMultiOracle.sol
- contracts/oracles/compound/CompoundRateOracle.sol
- contracts/oracles/uniswap/UniswapV3Oracle.sol
- package.json
- test/012_oracles_composite.ts
- yarn.lock
Composite oracles store other IOracle contracts as sources, and for any given pair of (base, quote) can also store a path.
When (base, quote) is requested, the Composite Oracle checks if it has a path, and if so it returns the product of all (base, quote) pairs as in (base, path0) * (path0, path1) * ... * (pathN-1 pathN) * (pathN, quote).
> Composite oracles

- contracts/FYToken.sol
- contracts/Witch.sol
- test/031_fyToken.ts
- test/081_witch.ts
- test/shared/fixtures.ts
> Allow to point to new contracts consistently

- contracts/Witch.sol
> Witch::payAll doesn't end auction

- contracts/Witch.sol
- test/081_witch.ts
> test: delete vaults after payAll

- contracts/Cauldron.sol
Test to evaluate whether we want `_tweak` to check that `art` or `ink` are zero before changing `seriesId` or `ilkId` respectively.
The code is cleaner, but gas cost of `roll` raises from 78399 to 85818. Discuss.
> tweak: check data integrity in `_tweak`

- contracts/Wand.sol
- contracts/Witch.sol
- package.json
- test/081_witch.ts
- test/shared/fixtures.ts
Now we can set a limit on how much of a given collateral can be under auction at any given time.
Gas cost is 5k to 20k higher for all functions, although I would estimate a long term average of 7.5K
> Limit on collateral concurrently under auction

- package.json
Publishing as 0.15.0 to include the YearnVaultMultiOracle
> npm: 0.15.0-rc0

- contracts/mocks/ConvexYieldWrapperMock.sol
- contracts/utils/convex/ConvexYieldWrapper.sol
Fixes for:
- https://github.com/code-423n4/2022-01-yield-findings/issues/111
- https://github.com/code-423n4/2022-01-yield-findings/issues/107
> Fix to optimize `addVault` & `removeVault` code in ConvexYieldWrapper

- contracts/utils/convex/ConvexStakingWrapper.sol
- contracts/utils/convex/ConvexYieldWrapper.sol
Fix for:
- https://github.com/code-423n4/2022-01-yield-findings/issues/14
> ConvexYieldWrapper: modified for loop initialization to save gas

- contracts/utils/convex/ConvexStakingWrapper.sol
Fix for issue
- https://github.com/code-423n4/2022-01-yield-findings/issues/74
> added nonReentrant to functions

- contracts/mocks/ConvexPoolMock.sol
- contracts/utils/convex/ConvexStakingWrapper.sol
Fix for issue: https://github.com/code-423n4/2022-01-yield-findings/issues/101
> Removed unnecessary += to save gas

- contracts/utils/convex/ConvexStakingWrapper.sol
- contracts/utils/convex/ConvexYieldWrapper.sol
Fixes for the following:
- https://github.com/code-423n4/2022-01-yield-findings/issues/67
- https://github.com/code-423n4/2022-01-yield-findings/issues/65
- https://github.com/code-423n4/2022-01-yield-findings/issues/64
- https://github.com/code-423n4/2022-01-yield-findings/issues/112
- #343
> ConvexYieldWrapper: added unchecked blocks for gas saving

- contracts/utils/convex/ConvexStakingWrapper.sol
- contracts/utils/convex/ConvexYieldWrapper.sol
- https://github.com/code-423n4/2022-01-yield-findings/issues/75
> ConvexYieldWrapper: removed the AccessControl

- contracts/mocks/ConvexYieldWrapperMock.sol
- contracts/utils/convex/ConvexModule.sol
- contracts/utils/convex/ConvexYieldWrapper.sol
- test/092_convex_wrapper.ts
- https://github.com/code-423n4/2022-01-yield-findings/issues/39
> ConvexYieldWrapper: made removeVault pattern similar to addVault in `ConvexModule`

- contracts/utils/convex/ConvexStakingWrapper.sol
- https://github.com/code-423n4/2022-01-yield-findings/issues/72
> ConvexYieldWrapper: call safeTransfer directly from library

- contracts/utils/convex/ConvexYieldWrapper.sol
- test/092_convex_wrapper.ts
Fix for:
- https://github.com/code-423n4/2022-01-yield-findings/issues/45
> ConvexYieldWrapper: throw error when zero address passed in removeVault

- contracts/oracles/convex/Cvx3CrvOracle.sol
- contracts/utils/convex/ConvexStakingWrapper.sol
Fix for:
- https://github.com/code-423n4/2022-01-yield-findings/issues/60
> ConvexYieldWrapper: removed unused named returns

- contracts/utils/convex/ConvexStakingWrapper.sol
- https://github.com/code-423n4/2022-01-yield-findings/issues/58
> ConvexYieldWrapper: Tight variable packing in `ConvexStakingWrapper.sol`

- contracts/utils/convex/ConvexStakingWrapper.sol
- https://github.com/code-423n4/2022-01-yield-findings/issues/95
> ConvexYieldWrapper: modified earned function to the latest one

- .gitmodules
- contracts/foundry-tests/Witch.t.sol
- contracts/foundry-tests/oracles/PoolOracle.t.sol
- contracts/foundry-tests/oracles/YieldSpaceMultiOracle.t.sol
- contracts/foundry-tests/utils/Mocks.sol
- contracts/foundry-tests/utils/TestConstants.sol
- contracts/oracles/yieldspace/IPoolOracle.sol
- contracts/oracles/yieldspace/PoolOracle.sol
- contracts/oracles/yieldspace/YieldSpaceMultiOracle.sol
- package.json
- remappings.txt
- yarn.lock
- forge install: yieldspace-interfaces
- ported generic YieldSpaceMultiOracle from Contango
- rename sut
- forge install: yieldspace-v2
- Add YieldSpaceMultiOracle
> YieldSpaceMultiOracle

- packages/hardhat/test/017_oracles_accumulator.ts
- packages/hardhat/test/018_oracles_chainlink_usd.ts
- packages/hardhat/test/020_oracles_notional.ts
- packages/hardhat/test/024_join_convex.ts
- packages/hardhat/test/081_witch.ts
these tests are failing for unknown reasons.
skipping for now but alberto says they will be fixed/rewritten later
> buildfix: skip failing tests

- packages/foundry/contracts/test/WitchV2.t.sol
- packages/foundry/contracts/test/utils/Mocks.sol
- packages/foundry/contracts/witch/WitchDataTypes.sol
- packages/foundry/contracts/witch/WitchV2.sol
- Use cauldron params to cater for dust
- small improvements on WitchV2 tests
> Witch to share dust params with Cauldron

- .gitignore
- README.md
Adds support for `.env` files by adding to `.gitignore` and updating documentation.
> Add support for `.env` files

- packages/foundry/contracts/other/notional/INotionalJoin.sol
- packages/foundry/contracts/other/notional/NotionalJoin.sol
- packages/foundry/contracts/test/other/notional/NotionalJoin.t.sol
- packages/foundry/package.json
Rename `id` to `fCashId` on NotionalJoin.sol for clarity
> tweak: id -> fCashId

- packages/foundry/contracts/other/notional/NotionalJoin.sol
The use of `accrual` to convert from fCash units to underlying units was obscure, and only @bbonanno stopped me from pulling the brakes.
> mama I had a heart attack last night

- packages/foundry/contracts/Witch.sol
In the case that there are two Witches, and they haven't been correctly set to not steal vaults from each other, we would arrive to a state where in a Witch or both remain auctions that can't operate in the vaults that they are auctioning, and can't be cleared either.
This can happen as well when migrating from Witch v1 to v2, or in other future cases where we allow to `seize` vaults.
> feat: allow to clear auctions

- packages/foundry/contracts/modules/RepayFromLadleModule.sol
- packages/foundry/contracts/oracles/strategy/StrategyOracle.sol
- packages/foundry/contracts/test/modules/RepayFromLadleModule.t.sol
- packages/foundry/contracts/test/oracles/StrategyOracle.t.sol
- packages/foundry/package.json
- packages/hardhat/package.json
> Rename to RepayFromLadleModule

- README.md
- packages/foundry/contracts/Ladle.sol
- packages/foundry/contracts/interfaces/ILadle.sol
- packages/foundry/package.json
- packages/foundry/remappings.txt
I don't know why this works but when I made these changes in `strategy-v2`, the tests all passed.
> fix: ILadle.sol import error

- packages/foundry/contracts/interfaces/ICauldron.sol
- packages/foundry/contracts/interfaces/ILadle.sol
- packages/foundry/contracts/mocks/ConvexPoolMock.sol
- packages/foundry/contracts/oracles/strategy/StrategyOracle.sol
- packages/foundry/contracts/oracles/yearn/YearnVaultMultiOracle.sol
- packages/foundry/contracts/other/notional/NotionalJoin.sol
- packages/foundry/contracts/test/other/notional/NotionalJoin.t.sol
- packages/foundry/contracts/test/other/notional/NotionalJoinHarness.t.sol
- packages/foundry/contracts/test/utils/TestExtensions.sol
Mostly adds the correct function modifier, gets rid of unused vars, shadowed parameters.
> Fix most compiler warnings

- package.json
- src/oracles/IdentityOracle.sol
- src/other/notional/NotionalMultiOracle.sol
- src/test/oracles/IdentityOracle.t.sol
An identity oracle which returns an exchange rate of 1:1 taking decimals into consideration for the conversion
> Identity Oracle

- package.json
- src/FYToken.sol
- src/test/fyToken/FYToken.t.sol
- src/test/fyToken/FYTokenFlash.t.sol
The mature on first redemption feature was broken and didn't actually work. The unit test for it was equally broken. Fixed now.
> Fix: First redeem triggers mature
