yieldprotocol/vault-v2

- hardhat.config.ts
- package.json
I've found this a very handy fix. Basically, removes the `artifacts` and `typechain` folders before compiling for tests. Not linked to any particular issue.
> Clean builds and rebuild before tests

- contracts/Cauldron.sol
- contracts/Ladle.sol
- contracts/Witch.sol
- package.json
- test/051_cauldron_admin.ts
- test/081_witch.ts
- test/shared/fixtures.ts
- test/shared/helpers.ts
- yarn.lock
Fixes #214 with a refactor of Witch, and with it a number of issues in the C4 report ([8](https://github.com/code-423n4/2021-05-yield-findings/issues/8), [44](https://github.com/code-423n4/2021-05-yield-findings/issues/44), [71](https://github.com/code-423n4/2021-05-yield-findings/issues/71))
- Removed parallel liquidation engines feature, which was complex and a source of exploits.
- Included a DUST parameter
- Debt accrual now taken into account for liquidations
- payAll function to liquidate a whole vault after maturity
There is an issue unrelated to this PR making CI fail. I believe it has something to do with the chain not being reverted to the previous block after advancing time in the 031 test file.
> Witch refactor

- contracts/Ladle.sol
- hardhat.config.ts
Follows the pattern used in PoolRouter.sol.
To fit the extra code the optimization runs had to be decreased again, to 1000 runs. The complexity of `batch` and the size it imposes in `Ladle` is starting to make a strong case for using the regular `multicall` approach.
> feat: ladle.batch collates the results of the actions

- contracts/FYTokenFactory.sol
- contracts/JoinFactory.sol
- test/021_join.ts
- test/022_join_flash.ts
- test/051_cauldron_admin.ts
- test/060_ladle_admin.ts
- test/shared/fixtures.ts
If anyone can use our factories to create Joins and FYTokens, they could front-run us for a denial-of-service attack. It would only stop us from adding assets, but it would be annoying. Better to fix it now.
> fix: make factories auth to avoid griefing attacks

- contracts/Ladle.sol
- contracts/LadleStorage.sol
- contracts/mocks/WETH9Mock.sol
- contracts/oracles/composite/CompositeMultiOracle.sol
- hardhat.config.ts
- src/constants.ts
- src/ladleWrapper.ts
- test/070_ladle_batch.ts
The main changes are:
1. All functions are now `external payable`. They can be executed in a batch or on their own. To make the generalized use of `payable` safe the contract never uses `msg.value`.
2. The vault cache is now done in an storage variable, which costs no gas if used in a batch because it returns to zero at the end of the batch. To avoid scenarios where a vault is intentionally left in the cache after the transaction to carry out an attack, only the vaultId is cached, and the vault is retrieved and matched against msg.sender for each action. This is cheap after the Berlin fork.
3. Optimization runs have been raised from 2500 to 20000
> Use ENS-style Multicall

- contracts/Ladle.sol
- src/ladleWrapper.ts
- test/072_module_transfer.ts
Allow the Ladle to transfer known assets to known modules, so that the modules can be the first action in a batch
> feat: transferToModule

- contracts/Ladle.sol
- package.json
- test/063_ladle_vaults.ts
When building a vault through the Ladle, if the Cauldron reverts for any reason other than the vaultId already being used, the Ladle will fall into an infinite vaultId generating and vault building loop. Fun, but expensive.
> fix: ladle.build infinite loop

- contracts/FYToken.sol
- test/031_fyToken.ts
If the `amount` to redeem is 0, the fyToken contract redeems its own balance, as with uniswap v2.
> Redeem from fyToken contract

- contracts/Ladle.sol
- hardhat.config.ts
feat: return collateral in repayFrom*
We know we only use this when removing liquidity that was added with borrow and pool, so we can safely assume the amount of debt removed can be also the amount of collateral removed. If used in any other context, it might revert, and that's fine.
> feat: return collateral in repayFrom*

- contracts/Ladle.sol
- package.json
- test/066_ladle_repay_from.ts
Otherwise `repayFromLadle` and `closeFromLadle` will keep assets in Ladle when called due to slippage making it too close to call whether debt will be repaid or not.
> fix: return assets in ladle if no debt was repaid

- contracts/oracles/uniswap/UniswapV3Oracle.sol
- package.json
- test/015_oracles_uniswap.ts
Remove the setSecondsAgo as a separate function
1. Removed the function to setSecondsAgo and moved setting it to the setSource function.
2. Source data will store the secondsAgo value for each source
3. Modified test to reflect the changes in the setSource function 
Run [015_oracles_uniswap](https://github.com/yieldprotocol/vault-v2/blob/tweak/uniswapv3-oracle/test/015_oracles_uniswap.ts)
> tweak: removed setSecondsAgo function in UniswapV3 Oracle

- test/017_oracles_accumulator.ts
- test/017_oracles_yearnvault.ts
+ `ff`: log block timestamp pre/post fast forwarding
* 017_oracles_yearnvault: fix expect()...to.emit() syntaxis, expected event args
> Tests: extra debugging, minor fix

- contracts/FYToken.sol
- package.json
- test/032_fyToken_flash.ts
- test/shared/fixtures.ts
*Summary*
Disable flash loans by default on fyToken, following the Join pattern.
*Details*
We can be subject to DoS attacks when releasing new series, particularly if doing so at the same time that we roll a strategy onto them.
If we deploy a pool and we don't roll a strategy onto it in the same transaction, a malicious actor can skew the ratio in the pool using the free fyToken flash loans, just to make our slippage protection kick in and revert the governance action. While no funds would be lost, service continuity would be affected.
This PR sets the fyToken flash loans to be disabled by default, along with allowing to charge a fee in case that would be necessary to protect from unforeseen attacks.
> Disable fyToken flash loans by default

- contracts/utils/convex/ConvexStakingWrapper.sol
Fix for the following issue:
-https://github.com/code-423n4/2022-01-yield-findings/issues/102
> Optimized `nonReentrant` on ConvexYieldWrapper

- contracts/mocks/CurveProxy.sol
- contracts/mocks/TokenProxy.sol
- contracts/utils/convex/ConvexStakingWrapper.sol
- contracts/utils/convex/ConvexYieldWrapper.sol
- package.json
- test/092_convex_wrapper.ts
Mock the `crv` & `convexbooster` contract such that we can use the `ConvexYieldWrapper` directly in tests rather than creating a separate `ConvexYieldWrapperMock`
> ConvexYieldWrapper: Mock contracts for tests

- contracts/Join.sol
- contracts/Ladle.sol
- contracts/other/README.md
- contracts/other/notional/ERC1155.sol
- contracts/other/notional/ERC1155Mock.sol
- contracts/other/notional/Join1155.sol
- contracts/other/notional/NotionalMultiOracle.sol
- contracts/other/notional/README.md
- contracts/other/notional/Transfer1155Module.sol
- package.json
- test/020_oracles_notional.ts
- test/023_join1155.ts
- test/074_module_transferERC1155.ts
- Regular Join that takes ERC1155 assets, but is locked to a single id. No flash loans.
- Minimal Ladle module to transfer ERC1155 assets. No permit.
- Minimal Oracle that prices fCash at face value.
Check the README for more details.
All files have been stored in `contracts/other/notional`. We can have a discussion on how to organize this repo better.
1. I think that we could keep specific integration contracts in `other`, which would also mean moving a bunch of oracles.
2. The ERC1155.sol contract can be imported from solmate, or copied into `utils`.
3. The `Join1155` could go into a `joins` folder since it is not specific to any solution.
> Notional fCash as collateral

- contracts/constants/Constants.sol
This PR is for the marking of the constants `CHI`, `RATE`, and `ETH` in `Constants.sol` with `constant` keyword. Closes #380
> feat: mark constants in Constants.sol as constant

- .github/workflows/ci.yml
This PR adds the capacity for the CI to use mainnet forking with forge through the use of an RPC url.
> Update CI for use with forge mainnet forking

- .github/workflows/ci.yml
Adds Alchemy RPC to `forge snapshot` so that tests using mainnet forking do not break on this run.
> Fix `forge snapshot` for use with tests that use mainnet forking

- .gitignore
- packages/foundry/contracts/Witch.sol
- packages/foundry/contracts/test/Witch.t.sol
- Fix issue with invalid auctioneer reward address
- Code simplification
- Use auction state to determine if a vault is already under auction or not
- Cater for all the dust scenarios
- Check that config is valid for base/ilk pair before starting an auction
- Remove initialOffer = 0 as valid value
- Auto disable the witch after it can't handle the timestamp
- Merge setLine & setLimit
- refactor _payInk
- add .env to .gitignore
> witchAuditFixes

- .gitignore
- packages/foundry/contracts/Witch.sol
- packages/foundry/contracts/test/Witch.t.sol
Testing the bot with all the main net history we discovered that some vaults made the auction calculation fail.
Those vaults are broken in many other ways, but made me realised that any vault for which the debt is below the min debt would make the auction calculation fail.
I think it needs to be addressed cause otherwise you can never raise the min debt unless you ensure there are 0 vaults below the new min, which I think is probably not an option.
> Witch bugfix

- packages/foundry/contracts/FYToken.sol
There was an instance where the accrual calculation was done manually, instead of calling `_convertToUnderlying`
> Reuse code in `redeem`

- packages/foundry/contracts/other/notional/NotionalJoin.sol
- packages/foundry/contracts/test/other/notional/NotionalJoin.t.sol
- packages/foundry/contracts/test/other/notional/NotionalJoinHarness.t.sol
- packages/foundry/contracts/test/other/notional/NotionalTypes.sol
- packages/foundry/contracts/test/other/notional/testHarness.sh
- packages/foundry/foundry.toml
- packages/foundry/package.json
Draft fix for Notional sending unwrapped ETH on redemption to the NotionalJoin.
Tests still not working because Notional is hard.
Published as 0.16.7-rc.0
> fix: receive and wrap ETH from Notional

- packages/foundry/contracts/interfaces/ILadle.sol
- packages/foundry/contracts/test/modules/HealerModule.t.sol
- packages/foundry/contracts/test/modules/RepayFromLadleModule.t.sol
`ILadle.sol` functions were missing `payable` modifier which made it unable to specify a `value` when calling them.
Also the module tests used a now deprecated `ILadleCustom` interface from when the module functions were missing from a previous version of `ILadle`. This has been fixed. 
As an aside, I've been using `forge fmt` on my commits lately which we should probably integrate into the CI. (That's why there's so many spacing changes)
> Update `ILadle` functions to be `payable`
